name: zMenuConvert
author: Maxlego08
main: fr.maxlego08.convert.ConvertPlugin
website: https://groupez.dev
version: 1.0.0
api-version: 1.13
depend:
- zMenu
softdepend:
- DeluxeMenus
- GUIPlus
commands: