name: zMenuConvert
author: Maxlego08
main: fr.maxlego08.convert.ConvertPlugin
website: https://groupez.dev/resources/zmenuconvert.266
version: 1.0.5
api-version: 1.13
depend:
- zMenu
softdepend:
- DeluxeMenus
- GUIPlus
commands: